### ISSUE TITLE
Selecting Pending TX gives error..

### ISSUE THREAD

**Issue by pir8radio** [signum-network/signum-explorer#25]
Clicking a pending tx throws an error. I'll look into it, just logging it here.

![image](https://user-images.githubusercontent.com/16748696/145738743-3d08013f-b933-4efe-9e6f-5b180955f1e9.png)

`[13/Dec/2021 01:18:20] ERROR [django.request:224] Internal Server Error: /tx/14316452339719770242
Traceback (most recent call last):
  File "/home/signum/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/signum/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 188, in render
    values = {
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/loader_tags.py", line 189, in <dictcomp>
    name: var.resolve(context)
  File "/home/signum/.local/lib/python3.8/site-packages/django/template/base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/signum/Signum_Apps/Explorer/scan/templatetags/burst_tags.py", line 217, in tx_load_recipients
    data = MultiOutPack().unpack_multi_out(tx.attachment_bytes)
  File "/home/signum/Signum_Apps/Explorer/burst/libs/multiout.py", line 29, in unpack_multi_out
    version, nums = self._unpack_header(data[:2])
TypeError: 'NoneType' object is not subscriptable`

**Comment by jjos2372** [comment]
It is working for testnet, so we need to check what is missing with the stable node to circumvent the problem.
